"""add_partial_note_to_tickets

Revision ID: 07bef710acde
Revises: 959d099f05e3
Create Date: 2026-06-18 11:42:44.797026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bef710acde'
down_revision: Union[str, Sequence[str], None] = '959d099f05e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('partial_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'partial_note')
    # ### end Alembic commands ###
